export const ADD_ARTICLE = "ADD_ARTICLE";
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const SORT_PRODUCTS_PENDING = 'SORT_PRODUCTS_PENDING';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const SEARCH_PRODUCTS_PENDING = 'SEARCH_PRODUCTS_PENDING';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';